### ISSUE TITLE
 'FileDropper.xml' does not conform to the XML schema

### ISSUE THREAD

**Issue by MichielArts** [JelteMX/mendix-file-dropper#13]
When i download the widget from the appstore using mendix modeler version 7.23.8, i get following error:

Package 'D:\**********\widgets\com.mendix.widget.custom.FileDropper.mpk': Widget XML file 'FileDropper.xml' does not conform to the XML schema:
The element 'properties' in namespace 'http://www.mendix.com/widget/1.0/' has invalid child element 'propertyGroup' in namespace 'http://www.mendix.com/widget/1.0/'. List of possible elements expected: 'property' in namespace 'http://www.mendix.com/widget/1.0/'.

I am not (yet) sure if the widget works after getting this error, i will keep you posted.

**Comment by MichielArts** [comment]
![image](https://user-images.githubusercontent.com/55432127/91159576-88220500-e6c8-11ea-9069-829484fcec80.png)

The widget does not work for me.

**Comment by MichielArts** [comment]
The widget does not work for me: "some widget packages could not be read" is reported by the modeler.

**Comment by JelteMX** [comment]
The File Dropper widget is intended for Mendix 8.0.0 and higher. This will never work in Mendix 7
