### ISSUE TITLE
E-mail messages extension and MIMEType are not recognized

### ISSUE THREAD

**Issue by jverhagen** [JelteMX/mendix-file-dropper#7]
When uploading a save e-mail message from outlook (*.msg) this files extension and MIMEType are not recognized and left empty. The files icon show "unknown" as it's type.

![image](https://user-images.githubusercontent.com/19779012/76755758-ba781f80-6784-11ea-97c5-b77d48ac86e1.png)

**Comment by JelteMX** [comment]
This is purely the browser not being able to understand the file type, based on the structure of the file. There isn't a lot we can do about it.

In terms of UI, you can switch off the label: https://github.com/JelteMX/mendix-file-dropper#5-ui
