### ISSUE TITLE
Mendix widget Filedropper widget gives error: multipleDefine and Invariant Violation: Minified React error #130

### ISSUE THREAD

**Issue by Abhijit-Bhattacharya-Epiuse** [JelteMX/mendix-file-dropper#8]
Subject: Mendix widget Filedropper widget gives error: multipleDefine and Invariant Violation: Minified React error #130
Attached a sample project to see the issue by running it.

We are facing an issue with a Mendix created react js widget Filedropper.

When a page contains the Filedropper widget and I insert the below mentioned script in the head of the html, then I get the error on page load as show in log below.

The issue could be that both the script as well as the widget tries to load same library but I am not sure.. Can you help me find how we need to fix the widget?

Logs:
mxui.js?637190221705796834:73 Error: multipleDefine
at d (mxui.js?637190221705796834:5)
at Ze (mxui.js?637190221705796834:5)
at mxui.js?637190221705796834:5
at c (mxui.js?637190221705796834:5)
at et (mxui.js?637190221705796834:5)
at r (mxui.js?637190221705796834:5)
at HTMLScriptElement.<anonymous> (mxui.js?637190221705796834:5)
(anonymous) @ mxui.js?637190221705796834:73
mxui.js?637190221705796834:73 Loading module failed! Check console log for more detailed debug information.
(anonymous) @ mxui.js?637190221705796834:73
mxui.js?637190221705796834:73 Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at a (http://localhost:8083/mxclientsystem/mxui/mxui.js?637190221705796834:55:257)
at s (http://localhost:8083/mxclientsystem/mxui/mxui.js?637190221705796834:55:527)

-----------------------

FYI, the script I insert in the head element is below (it is for a a completely separate purpose and yet it is stopping the Filedropper widget from loading):
<script type="text/javascript">
var sdkInstance="appInsightsSDK";window[sdkInstance]="appInsights";var aiName=window[sdkInstance],aisdk=window[aiName]||function(e){function n(e){t[e]=function(){var n=arguments;t.queue.push(function(){t[e].apply(t,n)})}}var t={config:e};t.initialize=!0;var i=document,a=window;setTimeout(function(){var n=i.createElement("script");n.src=e.url||"https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js",i.getElementsByTagName("script")[0].parentNode.appendChild(n)});try{t.cookie=i.cookie}catch(e){}t.queue=[],t.version=2;for(var r=["Event","PageView","Exception","Trace","DependencyData","Metric","PageViewPerformance"];r.length;)n("track"+r.pop());n("startTrackPage"),n("stopTrackPage");var s="Track"+r[0];if(n("start"+s),n("stop"+s),n("addTelemetryInitializer"),n("setAuthenticatedUserContext"),n("clearAuthenticatedUserContext"),n("flush"),t.SeverityLevel={Verbose:0,Information:1,Warning:2,Error:3,Critical:4},!(!0===e.disableExceptionTracking||e.extensionConfig&&e.extensionConfig.ApplicationInsightsAnalytics&&!0===e.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking)){n("_"+(r="onerror"));var o=a[r];a[r]=function(e,n,i,a,s){var c=o&&o(e,n,i,a,s);return!0!==c&&t["_"+r]({message:e,url:n,lineNumber:i,columnNumber:a,error:s}),c},e.autoExceptionInstrumented=!0}return t}(
{
instrumentationKey:"59805d60-2856-44d6-be59-84d5de467777"
}
);window[aiName]=aisdk,aisdk.queue&&0===aisdk.queue.length&&aisdk.trackPageView({});
</script>

Any pointers would be appreciated.

**Comment by JelteMX** [comment]
I'll investigate the issue

**Comment by JelteMX** [comment]
I have checked your test-project, and I am getting errors even when I remove the FileDropper from the page. When I do have the FileDropper on the page, I see the widget working just fine.
All in all this means that the widget itself is not the culprit, but your tracking script. Closing this issue
